### ISSUE TITLE
Added OP5util to OP5 Community page

### ISSUE THREAD

**Issue by fmikker** [np422/Op5util#1]
Thank you for your addition in the IRC channel #op5, added your tool to https://kb.op5.com/display/COMMUNITY/OP5+Ecosystem

**Comment by np422** [comment]
Hi there, please feel free to include a screenshot or two linked from the Readme.md on the community page. (Version-no bumped today and new screenshots added.)

And I'm closing this issue as not-a-bug, but please feel free to continue to leave any more feedback here or contact me by mail.

**Comment by fmikker** [comment]
Screenshots added, thank you for the feedback!
